### ISSUE TITLE
WAIC-TEST-0024-02 nav 要素への直接移動

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#10]
直前または直後の nav 要素へ直接移動できるかどうか確認するためのテスト。
nav 要素単体で直接移動ができるのか、またできない場合 aria-label などと組み合わせて移動できるかどうかという情報を調べたい。

**Comment by cocktailz** [comment]
nav 要素というよりは、直前直後のランドマークに移動する機能があるのでそれのテストにしたほうがよいのではないか。

**Comment by cocktailz** [comment]
ランドマークで飛ぶのか、ナビゲーションに飛ぶ専用の機能がない場合NGにするのか？

**Comment by cocktailz** [comment]
JAWSは、次のランドマークへ移動する機能と、role="main" に移動する機能がある。
2つの nav 要素の間にmainやcontentinfoなどほかのランドマークがあることを許容するのかどうか。

**Comment by cocktailz** [comment]
nav 要素の間にランドマークがたくさんある場合、nav 同士を直接移動できる方が便利だとは思う。

**Comment by cocktailz** [comment]
nav よりmain のほうがテストの優先度が高いのではないか。

**Comment by cocktailz** [comment]
0024-02 は nav に直接移動できるかの照すtにして、別途ランドマークに飛べるかのテストを作る。

**Comment by cocktailz** [comment]
nav 要素の内容をスキップして末尾に飛ぶことを求めてるんじゃないか？
ナビゲーションをスキップしたいのであって、ナビゲーション間を飛べるテストがどのくらい重要なのか。

**Comment by cocktailz** [comment]
前後のランドマークに飛ぶ、
role=～に飛ぶ
role=main に飛ぶ

の3つを優先順位をあげてつくる

div role=main
main 
main role=main

ランドマークの先頭・末尾に移動する機能、
ランドマーク間を移動する機能

という場合分けでテストを作る。

**Comment by nishimotz** [comment]
現状 NVDA で使えるのはブラウズモードの1文字ナビゲーション
D と Shift+D で「次のランドマークに移動」「前のランドマークに移動」です。
これは Firefox, Chrome, IE11 で現状のテストに対して動作しています。

**Comment by SawadaStdDesign** [comment]
nav要素配下に直接a要素が並ぶとNVDAやNetReader+PC-Talkerで分けずに一度に読み上げられてしまうため、各a要素をdiv要素に入れるように変更。

**Comment by akiyamaa-cnt** [comment]
* nav 要素内の a 要素を div で包含する

**Comment by akiyamaa-cnt** [comment]
> nav要素配下に直接a要素が並ぶとNVDAやNetReader+PC-Talkerで分けずに一度に読み上げられてしまうため、各a要素をdiv要素に入れるように変更。

WAIC-TEST-0024-02 のみではなく、WAIC-TEST-0024-01 にも同様の記述があったので修正します。
