### ISSUE TITLE
WAIC-TEST-0030-01 aria-required 属性による必須項目の特定（input要素、select要素、textarea要素）

### ISSUE THREAD

**Issue by akiyamaa-cnt** [waic/as_test#116]
https://waic.jp/docs/WCAG21/Techniques/aria/ARIA2#example-1

**Comment by SawadaStdDesign** [comment]
- 「プロパティ」と「属性」が混在していますので「属性」に揃えましょう。
- 「テストコードのソース (抜粋)」がソース表示になっていないようです。ご確認ください。
- `type="text"`と`type="password"`がテストされますが、`type="radio"`や`type="checkbox"`など他のtypeのinput要素や、他のコントロール（`select`や`textarea`など）に対するテストが必要ないかどうかご検討ください。
- また、aria-required属性が設定されていない要素との対比が必要ないかどうかご検討ください。

**Comment by akiyamaa-cnt** [comment]
1月12日 WG2 にて。

* 「プロパティ」は「属性」へと書き換える。
    * 属性と記述すると間違う箇所以外は「属性」記述で統一する。
* 「テストコードのソース (抜粋)」がソース表示になっていないため、md を修正する。
* input[type="text"]、input[type="password"] のほか、select要素、input[type="radio"]、input[type="checkbox"]
    * select では、下記の 2種についてのテストファイルを実施する。
        * select 要素の最初の子要素が空ではない場合。
        * select 要素の最初の子要素が空の場合。
    * input[type="button"]、input[type="button"]、

**Comment by yuyaroid** [comment]
@akiyamaa-cnt 

非常に遅くなってしまったのですがコメントをもとにテストコードを修正しました。
よろしくお願いします。

**Comment by akiyamaa-cnt** [comment]
（全体レビュー中。フィードバックお待ちしております）

**Comment by akiyamaa-cnt** [comment]
8月10日の WG2 にて議論。

下記にてコメントの修正が全て反映されていることを確認した。
マージして良い。
https://github.com/waic/as_test/issues/116#issuecomment-1010702828

**Comment by akiyamaa-cnt** [comment]
テストタイトルを以下のように修正。

* aria-required 属性による必須項目の特定（xxxxxx）
    * xxxxxx の部分は、他の事例との違いを示す。

**Comment by akiyamaa-cnt** [comment]
2022年10月WG2 にて確認。
こちらで問題なし。
