### ISSUE TITLE
WAIC-TEST-0030-02 aria-required プロパティによって必須項目を特定する（事例2）

### ISSUE THREAD

**Issue by akiyamaa-cnt** [waic/as_test#117]
https://waic.jp/docs/WCAG21/Techniques/aria/ARIA2#example-2

**Comment by akiyamaa-cnt** [comment]
1月12日 WG2 にて議論。
本テストケースは削除する。

**Comment by yuyaroid** [comment]
必須であることを示す文字が違うだけであり、テストそのものが不要であるため、こちらのテストケースは削除します。
