### ISSUE TITLE
テストファイル用語案について

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#12]
諸熊さん、山田さんから用語の修正案をいただきました。

* [WAIC-TEST用語案_170914](https://github.com/waic/as_testfile2015/blob/dev/notification/WAIC-TEST%E7%94%A8%E8%AA%9E%E6%A1%88_170914.txt)
* [コメント_6月16日](https://github.com/waic/as_testfile2015/blob/dev/notification/%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88_6%E6%9C%8816%E6%97%A5.txt)
* [改訂履歴_4月14日～9月14日](https://github.com/waic/as_testfile2015/blob/dev/notification/%E6%94%B9%E8%A8%82%E5%B1%A5%E6%AD%B4_4%E6%9C%8814%E6%97%A5%EF%BD%9E9%E6%9C%8814%E6%97%A5.txt)

コメントや修正案などこちらで議論を進めたいと思います。

**Comment by cocktailz** [comment]
「読み飛ばす」が用語案の1番最後にありますが、これは「利用頻度の高いコマンド」ではないので、「テスト手順や期待される結果に用いられる用語」のほうへ移動してはいかがでしょうか。

**Comment by Morokuma0406** [comment]
ジャンプコマンドと関連していたので、記載のように分類していましたが、確かに利用頻度はそれほど高くない(主にブロックスキップ時)という認識ですね。

**Comment by TakahitoYamada** [comment]
修正案:
通知される: 
読み上げカーソルが当該要素に差し掛かった時に、スクリーンリーダーが必要な情報を自動的に伝えること。

**Comment by SawadaStdDesign** [comment]
「何らかの手段」に記載されている「提供者」は、「支援技術の提供者」のように補った方が「誰なの？」ってならなくてよいと思います。
もしくは「支援技術ベンダー」とか。

**Comment by ma10** [comment]
テーブルモードについて。

まずそもそもこれはどこかで使われているんでしたっけ? (そもそも定義する必要があるんでしたっけ?)

それから、「また、テーブル要素の外側にある要素への読み上げカーソルの移動が無効となる。」というのを書いてしまうことによって、JAWSやNVDAのテーブル内セル・ナビゲーション機能はこれには当たらないことになるのに、その後でJAWS/NVDAについて記述しているのは分かりづらい印象です。

**Comment by SawadaStdDesign** [comment]
「何らかの手段」に記載されている要件の、キー配列をJIS X 6002-1980に限定しているのは、どういった理由からでしょうか？
（我が家にはJISキーボードがありませんので検証できなくなる？）

**Comment by ma10** [comment]
定義を読んでいたら、「差し掛かった時」は「読み上げさせた時」良いような気がしてきました。

ただ、そもそも「読み上げ」
と「読み上げさせる」が別の用語として定義されるというのは非常に分かりづらい印象です。

「読み上げ」の定義の中で、どういった場合に読み上げが実行されるのかということを書くことで、「読み上げさせる」をなくしても良いように思います。

**Comment by Morokuma0406** [comment]
テーブルモードについては、テーブル要素のテストの中で挙げられていたという認識です。「WAIC-TEST-0010」
また、JAWSやNVDAでテーブル要素内でのナビゲーション(alt+矢印キー、またはCtrl+Alt+矢印キー)を使っていると、選択中のテーブルの外には移動できないはずです。「テーブルの端」などと言って止まります。

**Comment by TakahitoYamada** [comment]
修正案:
読み上げさせる:
スクリーンリーダーが提供しているコマンドをユーザーが実行することによって、結果が音声で伝えられること。

これは、通知されるとの対比かなと思いました。
わかりにくい表現になっているかもしれません。

**Comment by Morokuma0406** [comment]
JIS X 6002-1980としたのは、「戻る」キーや「ブラウザ」きーなど、特定の操作を再現するキーを除外することを意図しています。

**Comment by ma10** [comment]
> テーブルモードについては、テーブル要素のテストの中で挙げられていたという認識です。「WAIC-TEST-0010」

ざっと検索しましたが見当たらないようです。
どこで使われているでしょうか?

**Comment by TakahitoYamada** [comment]
テーブルモードは定義しなくても良いような気がしてきた。テーブル内でのナビゲーションはテーブル固有の操作だけれども、NVDAもJAWSもモードを切り替えている訳ではないので。

**Comment by Morokuma0406** [comment]
当初、テストコード作成の過程で必要になるか否かも考慮してテーブルモードは検討していましたが、確かに今のテストでは必要無さそうですね。
更新にて削除しましょう。

**Comment by Morokuma0406** [comment]
一通り挙げられたものを9月15日のバージョンに反映したものを公開したいと思います。

**Comment by cocktailz** [comment]
「読み上げさせる」の定義が「伝えられること」という受け身で終わっているのが気になりました。

: スクリーンリーダーが提供しているコマンドを実行することによって、結果を音声で伝えさせること。

とするのはいかがでしょうか。

**Comment by TakahitoYamada** [comment]
「読み上げさせる」は受身な表現であるので、「読み上げ」あるいは「読み上げる」という表現に変更したい。

**Comment by TakahitoYamada** [comment]
読み上げる:
ユーザーが実行したコマンドに応じて、スクリーンリーダーが音声で情報を伝えること。あるいはスクリーンリーダーが自動的に音声で情報を伝えること。

**Comment by akiyamaa-cnt** [comment]
再度問題が見つかるようであれば、あらためて issue を立てる。
