### ISSUE TITLE
WAIC-TEST-0030-05 aria-required プロパティによって必須項目を特定する（事例5）

### ISSUE THREAD

**Issue by akiyamaa-cnt** [waic/as_test#120]
https://waic.jp/docs/WCAG21/Techniques/aria/ARIA2#example-5-adding-aria-required-property-via-script

**Comment by nishimotz** [comment]
関連するテスト
* 0030-01 は完成したが #170 がオープンしている
* 0030-02 と 0030-04 は却下された
* 0030-03 は #118
