### ISSUE TITLE
WAIC-TEST-0031-01 ユーザインタフェース コンポーネントの役割 (role) を明示するために、WAI-ARIA ロールを使用する（事例1）

### ISSUE THREAD

**Issue by akiyamaa-cnt** [waic/as_test#137]
https://waic.jp/docs/WCAG21/Techniques/aria/ARIA4#example-1-a-simple-toolbar

**Comment by akiyamaa-cnt** [comment]
__疑問点__
role="toolbar" が指定されている div 要素には、function が色々と指定されているが、本サンプルでは「 div 要素に role="toolbar" が指定されてること」のみを確認すれば良いか？
（ role="button" が指定されている img 要素に対する確認は不要か？ ）

**Comment by SawadaStdDesign** [comment]
WAI-ARIA Authoring Practices では img 要素のパターンから button 要素を使うパターンに変更されているので、現状の img 要素をボタンにする例にこだわる必要はないと思います（というかオススメしたくないです）。

また、このテストの目的が div 要素に限ったものであるなら、複雑なツールバーを作る必要もない気がします。

**Comment by akiyamaa-cnt** [comment]
@SawadaStdDesign 
レビューありがとうございます。

下記 2点を修正いたしました。
* div 要素に指定されている script に関する指定の削除。
* role="toolbar" の内部の img 要素を、button 要素へと変更。

**Comment by akiyamaa-cnt** [comment]
1月12日 WG2 にて議論。
修正は以下の点を実施。

1. div[role="toolbar"] に指定している tabindex 属性は不要。
2. 期待される結果を 2つにする。
    * 要素を順に移動した場合
    * tab キーで移動し button 要素にフォーカスした場合

**Comment by SawadaStdDesign** [comment]
期待される結果 (音声閲覧環境) 2. の「 toolbar に差し掛かっ」は不要ではないでしょうか？
句点「。」の有無が気になりました。（細かくて恐縮です）

1,2のその他の内容については反映されていることを確認しました。
問題ありません。

**Comment by akiyamaa-cnt** [comment]
修正しました！

> 期待される結果 (音声閲覧環境) 2. の「 toolbar に差し掛かっ」は不要ではないでしょうか？
> 句点「。」の有無が気になりました。（細かくて恐縮です）

**Comment by SawadaStdDesign** [comment]
確認しました。
問題ありません！
