### ISSUE TITLE
WAIC-TEST-0031-02 ユーザインタフェース コンポーネントの役割 (role) を明示するために、WAI-ARIA ロールを使用する（事例2）

### ISSUE THREAD

**Issue by akiyamaa-cnt** [waic/as_test#138]
https://waic.jp/docs/WCAG21/Techniques/aria/ARIA4#example-2-a-tree-widget

**Comment by SawadaStdDesign** [comment]
- このテスト対象のロールが tree であることを考えると、ユーザーエージェントによっては treeitem のレベルも読んでくれると思いますが、そのことを確認する必要はないでしょうか？
- この事例ではツリーの開閉ギミックが実装されているわけではないので、`role="tree"`が指定されている ul 要素の`tabindex="0"`はなくてもいいのではないでしょうか？

**Comment by akiyamaa-cnt** [comment]
1月12日 WG2 にて議論。
修正は以下の点を実施。

* tree, treeitem をどう読まれるか、次回議論

**Comment by akiyamaa-cnt** [comment]
2月9日 WG2 にて議論。
修正は以下の点を実施。

* 全ての ul, li 要素に tabindex="0" を付与する。

**Comment by akiyamaa-cnt** [comment]
下記の修正を実施しました。

> * 全ての ul, li 要素に tabindex="0" を付与する。
> * 「犬」の項目は削除。

**Comment by akiyamaa-cnt** [comment]
5月11日の wg2 にて、修正が問題ないことを確認。
