### ISSUE TITLE
WAIC-TEST-0032-01 リンクテキストの一部を非表示にするために、CSS を使用する（事例1）

### ISSUE THREAD

**Issue by sasak1ll** [waic/as_test#145]
https://waic.jp/docs/WCAG21/Techniques/css/C7#example-1

**Comment by akiyamaa-cnt** [comment]
@sasak1ll 

* テストファイルの「関連する要素や属性」の title 属性は、サンプルHTML 内で利用されていないため不要では？

**Comment by akiyamaa-cnt** [comment]
2月9日 WG2 にて議論。
修正は以下の点を実施。

* 期待される結果（音声閲覧環境）に、読み上げる内容を明確に記述しする。「ワシントンが経済成長を刺激する」と読まれることを明記する。
* 期待される結果（視覚閲覧環境）に 「ワシントンが経済成長を刺激する」が表示されてないことを記述する。

参考 : WAIC-TEST-0018-01.md

**Comment by sasak1ll** [comment]
下記 4点を修正いたしました。

- 「関連する要素や属性」の title 属性削除。
- テストコードのソース（抜粋）にCSS を含める。
- 期待される結果（音声閲覧環境）に、「ワシントンが経済成長を刺激する」と読まれることを明記。
- 期待される結果（視覚閲覧環境）に 「ワシントンが経済成長を刺激する」が表示されてないことを記述する。

**Comment by sasak1ll** [comment]
3月9日WG2にて以下2点について修正を実施することになりました。

- 期待される結果（音声閲覧環境）「ワシントンが経済成長を刺激する 全文表示」として読み上げられる、に修正。
- テストコードへのリンク設定を行う。

**Comment by akiyamaa-cnt** [comment]
8月10日の WG2 にて議論。

* 関連する達成方法に修正が必要。
* テストタイトルを以下のように修正する。
    * 「CSS によって不可視にされたリンクテキスト」。
        * 踏まえたい内容
            * リンクテキストで通知される。
            * 視覚的に隠す。
            * 非視覚環境で通知される。

**Comment by sasak1ll** [comment]
@akiyamaa-cnt 
テストのタイトルを
「リンクテキストの一部を非表示にするために、CSS を使用する」から
「CSS によって不可視にされたリンクテキスト」に修正しました。
ご確認のほどよろしくお願いいたします。

**Comment by akiyamaa-cnt** [comment]
@sasak1ll 
修正反映確認しました！
9月の WG2 にて確認後、問題なければマージとしましょう。
