### ISSUE TITLE
WAIC-TEST-0032-02リンクテキストの一部を非表示にするために、CSS を使用する（事例2）

### ISSUE THREAD

**Issue by sasak1ll** [waic/as_test#146]
https://waic.jp/docs/WCAG21/Techniques/css/C7#example-2

**Comment by akiyamaa-cnt** [comment]
@sasak1ll 

* テストファイルの「関連する要素や属性」の title 属性は、サンプルHTML 内で利用されていないため不要では？

**Comment by akiyamaa-cnt** [comment]
2月9日 WG2 にて議論。
s事例の 1 と同様の CSS のテスト

**Comment by sasak1ll** [comment]
中身としては事例1と同じになるため本テストケースは削除します。
