### ISSUE TITLE
WAIC-TEST-0034-01 単語内の文字間隔を制御するために、CSS の letter-spacing を使用する

### ISSUE THREAD

**Issue by sasak1ll** [waic/as_test#150]
https://waic.jp/docs/WCAG21/Techniques/css/C8#example-1-separating-characters-in-a-word-

**Comment by nishimotz** [comment]
* museum だと日本語音声エンジンが確実にミュージアムと読み上げるかどうかわからない
* 「東京都（そのまま）」「東京都（CSSで文字間隔をあける）」「東 京 都」の3種類を提示して、読み上げを比較してもらう

**Comment by SawadaStdDesign** [comment]
- テスト手順1：「東京都（そのまま）」と「東京都（CSSで文字間隔をあける）」の比較
- 期待される結果1：どちらも「とうきょうと」と読み上げられる。
- テスト手順2：「東京都（CSSで文字間隔をあける）」と「東 京 都」の比較
- 期待される結果2：一方は「とうきょうと」、もう一方は「ひがし　きょう　みやこ」のように1文字ずつ読み上げられる。

**Comment by sasak1ll** [comment]
下記 のレビュー内容を修正いたしました。

- テストの目的
- 関連する達成方法 (複数)
- テストコードのソース (抜粋)
- テスト手順 (視覚閲覧環境)
- 期待される結果 (視覚閲覧環境)
- テスト手順 (音声閲覧環境)
- 期待される結果 (音声閲覧環境)

**Comment by sasak1ll** [comment]
@akiyamaa-cnt
5月11日の WG2 でのレビュー内容を反映しました。
比較対象が把握できるようにそれぞれワードを特定する形で以下の通り修正

期待される結果 (視覚閲覧環境)
- CSSで文字間隔を調整した2番目のH2要素「東京都」の文字間隔の広がりが確認できる

テスト手順 (音声閲覧環境)
- 1番目のH2要素「東京都」と2番目のH2要素「東京都」を読み上げ、内容を確認
- 2番目のH2要素「東京都」と3番目のH2要素「東 京 都」を読み上げ、内容を確認

**Comment by akiyamaa-cnt** [comment]
@sasak1ll 
チームレビューとして、下記コメントしました。
ご確認お願いします。
https://github.com/waic/as_test/pull/156#pullrequestreview-1137548992

**Comment by akiyamaa-cnt** [comment]
2022年10月WG2 にて全体レビュー。

--- 

以下、変更点の概要です。

1. 前回の全体レビュー内容の反映
    * 「期待される結果 (視覚閲覧環境)」
    * 「テスト手順 (音声閲覧環境)」
2. 前回の全体レビュー内容以外の変更
    * 「期待される結果 (音声閲覧環境)」をリライト
        * 対応するテスト手順を追記。
    * 「テストの目的」をリライト
        * 達成方法 C9 の解説を踏まえ「letter-spacing プロパティの利用」を追加。
    * 「テストタイトル」をリライト
        * https://github.com/waic/as_test/issues/165 での実施事項を踏まえる。

作業 PR ：https://github.com/waic/as_test/pull/156

**Comment by akiyamaa-cnt** [comment]
全体レビュー
* 「期待される結果 (音声閲覧環境)」の 2 を修正する。
* 番号付きリストのマークダウン記法が誤ってるので直す。

**Comment by akiyamaa-cnt** [comment]
2022年11月 WG2 にて 全体レビュー。

--- 

変更点：10月のレビュー内容を反映。

> * 「期待される結果 (音声閲覧環境)」の 2 を修正する。
> * 番号付きリストのマークダウン記法が誤ってるので直す

**Comment by SawadaStdDesign** [comment]
2点とも修正されていることを確認しました。
問題ありません。

**Comment by SawadaStdDesign** [comment]
mergeしましたので、closeします
