### ISSUE TITLE
WAIC-TEST-0001-01 リンクの中にアイコン画像 (alt="") とテキストを並べた場合

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#16]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。
また、テスト実施時の注意点（音声閲覧環境）において、行読みモードとあった部分を、用語集の用語を用いて「テキストモード」としました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/58f255dc25602b72b26f49096570cea50cd3a8d1

**Comment by cocktailz** [comment]
クローズします
