### ISSUE TITLE
「テストのタイトル」の重複の解消

### ISSUE THREAD

**Issue by akiyamaa-cnt** [waic/as_test#162]
2022年5月の WG2 にて指摘。

下記テストケースの「テストのタイトル」が重複している。
過去のテストケースではタイトルを重複を避けているため、同様にタイトルの重複を解消する。

* WAIC-TEST-0028-0x
* WAIC-TEST-0029-0x
* WAIC-TEST-0031-0x

**Comment by akiyamaa-cnt** [comment]
既存のテストタイトルに以下を追記し、重複を解消。

__0028__
* (positionプロパティ)
* (positionプロパティ : 視覚的な表示順序の変更)

__0029__
* (button要素 : aria-label属性と併用)
* (input要素)
* (button要素)
* (input要素 : 隠された要素と関連付け)
* (input要素 : xhtml文書)
* (button要素 : aria-label属性と併用 : aria-describedby属性を script で生成)
* (button要素 : aria-labelledby属性と併用)
* (button要素 : 複数のaria-describedby属性値)

__0031__
* (div要素)
* (ul,li要素)

--- 

あわせて、0029-0x では「プロパティ」表記を「属性」表記へと変更。
（テストファイル作成時の修正指摘の反映漏れへの対応）

**Comment by akiyamaa-cnt** [comment]
（全体レビュー中。フィードバックお待ちしております）

**Comment by SawadaStdDesign** [comment]
@akiyamaa-cnt   
遅くなってしまい、申し訳ございません。
確認しました。

タイトルの重複が解消されていることは確認いたしました。
ただ、元々設定されているタイトルが達成基準のタイトルになっているため、「テストのタイトル」からテストの内容が把握できる状態になっていないようです。
例えば、
- 0028-01：CSSによる表示順序の変更（説明リスト）
- 0028-02：CSSによる表示順序の変更（見出しと段落）
の何のテストなのか判断できるようなタイトルにすることが望ましいです。

[テストの一覧](https://waic.jp/docs/as/info/index.html) を参考にしてみてください。

**Comment by akiyamaa-cnt** [comment]
@SawadaStdDesign 

ご確認ありがとうございます。

> ただ、元々設定されているタイトルが達成基準のタイトルになっているため、「テストのタイトル」からテストの内容が把握できる状態になっていないようです。

上記は issue の内容から外れるため、別 issue として対応を進めますね。

**Comment by akiyamaa-cnt** [comment]
> 別 issue として対応を進めますね。

下記 issue を発行しました。
https://github.com/waic/as_test/issues/165

**Comment by akiyamaa-cnt** [comment]
8月10日の WG2 にて確認済み。
master へとマージして良い。
