### ISSUE TITLE
「テストのタイトル」からテストの内容が把握できない

### ISSUE THREAD

**Issue by akiyamaa-cnt** [waic/as_test#165]
下記にて指摘。
https://github.com/waic/as_test/issues/162#issuecomment-1207428430

> 元々設定されているタイトルが達成基準のタイトルになっているため、「テストのタイトル」からテストの内容が把握できる状態になっていないようです。
> 例えば、
> 
> 0028-01：CSSによる表示順序の変更（説明リスト）
> 0028-02：CSSによる表示順序の変更（見出しと段落）
> のように何をするテストなのか想像できるようなタイトルにすることが望ましいです。
> 
> [テストの一覧](https://waic.jp/docs/as/info/index.html) を参考にしてみてください。

**Comment by akiyamaa-cnt** [comment]
全部の見直しはしんどいので、[テストの一覧](https://waic.jp/docs/as/info/index.html) に記載されていないものを対象とする。
（ 0027-01 から 0031-02 まで）

以下、確認対象となるテストタイトルの一覧。

* 0027-01: main ランドマークへの直接移動 (div 要素と role 属性 : main のみ)
* 0027-02: main ランドマークへの直接移動 (div 要素と role 属性 : main 以外のランドマークあり)
* 0027-03: main ランドマークへの直接移動 (main 要素 : main のみ)
* 0027-04: main ランドマークへの直接移動 (main 要素 : main 以外のランドマークあり)
* 0027-05: main ランドマークへの直接移動 (main 要素の role 属性 : main のみ)
* 0027-06: main ランドマークへの直接移動 (main 要素の role 属性 : main 以外のランドマークあり)
* 0028-01: 構造を示すマークアップに基づいてコンテンツを配置 (positionプロパティ)
* 0028-02: 構造を示すマークアップに基づいてコンテンツを配置 (positionプロパティ : 視覚的な表示順序の変更)
* 0029-01: ユーザインターフェース コントロールに対する説明ラベルを提供するために、aria-describedby 属性を使用する (button要素 : aria-label属性と併用)
* 0029-02: ユーザインターフェース コントロールに対する説明ラベルを提供するために、aria-describedby 属性を使用する (input要素)
* 0029-03: ユーザインターフェース コントロールに対する説明ラベルを提供するために、aria-describedby 属性を使用する (button要素)
* 0029-04: ユーザインターフェース コントロールに対する説明ラベルを提供するために、aria-describedby 属性を使用する (input要素 : 隠された要素と関連付け)
* 0029-05: ユーザインターフェース コントロールに対する説明ラベルを提供するために、aria-describedby 属性を使用する (input要素 : xhtml文書)
* 0029-06: ユーザインターフェース コントロールに対する説明ラベルを提供するために、aria-describedby 属性を使用する (button要素 : aria-label属性と併用 : aria-describedby属性を script で生成)
* 0031-01: ユーザインタフェース コンポーネントの役割 (role) を明示するために、WAI-ARIA ロールを使用する (div要素)
* 0031-02: ユーザインタフェース コンポーネントの役割 (role) を明示するために、WAI-ARIA ロールを使用する (ul,li要素)

**Comment by akiyamaa-cnt** [comment]
0031 では、role 属性の内容が通知されるかを確認している。
最低限の提示であれば「利用した role属性値」を、もう具体化するなら「利用した role属性値と対象要素」を示せば良さそう。

* __案1：「利用した role属性値」の場合__
    * 0031-01: role 属性 (toolbar)
    * 0031-02: role 属性 (tree, treeitem, group)
* __案2：「利用した role属性値と対象要素」の場合__
    * 0031-01: div 要素の role 属性 (toolbar)
    * 0031-02: ul, li 要素の role 属性 (tree, treeitem, group)

**Comment by akiyamaa-cnt** [comment]
0029 では、aria-describedby 属性による説明ラベルの提供を、様々な方法にて確認している。
既存タイトル末尾の括弧の内容が「様々な方法」を示しているので、それを含めれば良さそう。

* 0029-01: aria-describedby 属性 (button要素 : aria-label属性と併用)
* 0029-02: aria-describedby 属性 (input要素)
* 0029-03: aria-describedby 属性 (button要素)
* 0029-04: aria-describedby 属性 (input要素 : 隠された要素と関連付け)
* 0029-05: aria-describedby 属性 (input要素 : xhtml文書)
* 0029-06: aria-describedby 属性 (button要素 : aria-label属性と併用 : aria-describedby属性を script で生成)

**Comment by akiyamaa-cnt** [comment]
0028 では、CSSにより表示順序を変更した場合でも、構造順序通りに通知されるかを確認している。
テストでは position プロパティを用いて、複数の配置方法で確認を実施。
「利用プロパティと配置内容」と「利用した要素」のどちらを明示すべきか。

* 案1：__「利用したCSSプロパティと配置内容」の場合__
    * 0028-01: position プロパティによる表示順序の変更 (左右に配置)
    * 0028-02: position プロパティによる表示順序の変更 (上下を入れ替えて配置)
* 案2：__「利用した要素」__
    * 0028-01: CSSによる表示順序の変更 (説明リスト)
    * 0028-02: CSSによる表示順序の変更 (見出しと段落)

**Comment by akiyamaa-cnt** [comment]
0027 は特に問題無いように思える。
変更しない。

**Comment by akiyamaa-cnt** [comment]
以下、修正案。

* 0027
    * 変更不要。
* 0028
    * 2つの案を提示。どちらが良いか相談。
    * https://github.com/waic/as_test/issues/165#issuecomment-1209829293
* 0029
    * 修正案で問題無いか確認。
    * https://github.com/waic/as_test/issues/165#issuecomment-1209808662
* 0031
    * 2つの案を提示。どちらが良いか相談。
    * https://github.com/waic/as_test/issues/165#issuecomment-1209796023

**Comment by akiyamaa-cnt** [comment]
0029-07, 0029-08 で作業漏れあり。

**Comment by akiyamaa-cnt** [comment]
8月10日の WG2 にて議論。
下記にて進める。

> 0031 では、role 属性の内容が通知されるかを確認している。 最低限の提示であれば「利用した role属性値」を、もう具体化するなら「利用した role属性値と対象要素」を示せば良さそう。

検証するのは「意味を持たない要素への role 属性の指定」「意味を持つ要素への role 属性の指定」となるのでは？
案3 を提案する。

* __案3：「利用した role属性値と対象要素」の場合__
    * 0031-01: role 属性 (div 要素)
    * 0031-02: role 属性 (ul, li 要素)

**Comment by akiyamaa-cnt** [comment]
> 0029 では、aria-describedby 属性による説明ラベルの提供を、様々な方法にて確認している。 既存タイトル末尾の括弧の内容が「様々な方法」を示しているので、それを含めれば良さそう。

「属性で何ができるのか」まで示した方が良いのでは？

例: aria-describedby 属性による説明ラベルの提供 (button要素 : aria-label属性と併用)

**Comment by akiyamaa-cnt** [comment]
> 0028 

C6 の達成方法の解説には以下のようにある。
https://waic.jp/docs/WCAG-TECHS/C6.html

> この達成方法の目的は、スタイルシートが適用されていない場合でも意味のある提示を維持しながら、スタイルシートを介して視覚的外観をどのように向上させることができるかを示すことである。CSS2 の配置プロパティを使用して、コンテンツを利用者のビューポートの任意の位置に表示できる。構造的な要素を使用することで、スタイルが利用できない場合でもコンテンツの意味を判断できることを保証する。

配置プロパティを利用することが目的となるため、利用したプロパティが明示されていることが良い。

例：0028-02: CSSによる表示順序の変更 (positionプロパティ : 上下を入れ替えて配置)

**Comment by akiyamaa-cnt** [comment]
#166 にて、下記のように修正を反映しました。

* 0028
    * 下記コメントの例示の形で展開。
    * https://github.com/waic/as_test/issues/165#issuecomment-1210283593
* 0029
    * 下記コメントの例示の形で展開。
    * https://github.com/waic/as_test/issues/165#issuecomment-1210268911
* 0031
    * 前回の WG2 の結論から変更を加えています。
    * 修正具体
        * 0031-01: role 属性による役割の指定 (toolbar)
        * 0031-02: role 属性による役割の指定 (tree, treeitem, group)
    * 意図
        * 0029 と同様に、タイトルに「テストした属性」「属性で何をしているか」を含める。

**Comment by akiyamaa-cnt** [comment]
9月14日の WG2 にて。上記で問題なし。

**Comment by SawadaStdDesign** [comment]
@akiyamaa-cnt 
WAIC-TEST-0029-05のタイトルなのですが、
- aria-describedby 属性による説明ラベルの提供 (input要素 : xhtml文書)
の「xhtml」を「XHTML」にしたいです。
WG2で指摘できてなくてすみません...

**Comment by akiyamaa-cnt** [comment]
@SawadaStdDesign 
#167 にて修正 PR を作成しました。
ご確認をお願いいたします。

**Comment by akiyamaa-cnt** [comment]
#167 がマージされたので、こちらの Issue もクローズします。
