### ISSUE TITLE
WAIC-TEST-0030-03 aria-required 属性による必須項目の特定（role=radioを指定したラジオボタン）

### ISSUE THREAD

**Issue by yuyaroid** [waic/as_test#169]

**Comment by akiyamaa-cnt** [comment]
@yuyaroid 
過去に 0030-03 の Issue として下記を作成してたので、こちらを利用いただければと。
（ 0030-04, 0030-05 も同様に Issue のみ作成済みです ）
https://github.com/waic/as_test/issues/118

**Comment by yuyaroid** [comment]
@akiyamaa-cnt 

すみません…見落としていました。こちらはクローズします。
