### ISSUE TITLE
WAIC-TEST-0030-01 の修正：ラジオボタンに対する aria-required 属性指定の変更

### ISSUE THREAD

**Issue by akiyamaa-cnt** [waic/as_test#170]
2022年10月 WG2 全体レビューにて。

* ラジオボタン群を包括する fieldset 要素を作成する。
* fieldset 要素に対して、aria-required 属性を指定する。
* input[type="radio"] に対して指定している aria-required 属性を削除する。

**Comment by yuyaroid** [comment]
@akiyamaa-cnt @nishimotz 

直前となってしまいすみません。先月の全体レビューで指摘いただいていたテストケース00030-01の反映漏れを修正しました(#176 )。
ご確認お願いします。
