### ISSUE TITLE
「テストコードをユーザーエージェントで表示」のファイル名

### ISSUE THREAD

**Issue by nishimotz** [waic/as_test#178]
as_info を整備しようとして気づいたのですが、
https://github.com/waic/as_test/tree/master/WAIC-CODE
ファイル名が 0032-01 以降は WAIC-CODE ではなく WAIC-TEST で始まっています。
意図的な変更だったかどうか確認したいです。

**Comment by SawadaStdDesign** [comment]
@nishimotz ( Cc: @akiyamaa-cnt @sasak1ll @yuyaroid   
単なる間違いではないですかね？
（間違いやすく気が付きにくいという問題が露呈されたわけですが

**Comment by sasak1ll** [comment]
@nishimotz @SawadaStdDesign cc : @akiyamaa-cnt @yuyaroid
ご指摘の通り意図的な変更ではなく間違いになります、申し訳ございません！

**Comment by nishimotz** [comment]
PR #179 を作りました。
