### ISSUE TITLE
WAIC-TEST-0039-01 リンクの目的を示すために aria-label を使用する（事例1）

### ISSUE THREAD

**Issue by nishimotz** [waic/as_test#182]
8月9日WG2

* テストを作る人を増やし、マニュアルを改善する

進捗管理のため issue を作ります。タイトルは適宜変更してください。

**Comment by akiyamaa-cnt** [comment]
[ARIA8 事例1](https://waic.jp/translations/WCAG21/Techniques/aria/ARIA8)

**Comment by akiyamaa-cnt** [comment]
@nishimotz @sasak1ll  @yuyaroid 
0039-01 のテスト作成が終わりました。
https://github.com/waic/as_test/pull/187

チーム内レビュー（テストケースの記載漏れや、コード不備の確認）をお願いします。
9月の WG2 にて全体レビューに進むことができればと思います。

よろしくお願いいたします。
