### ISSUE TITLE
WAIC-TEST-0002-01 リンクの中にアイコン画像（代替テキストあり）、テキストの順で並べた場合

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#19]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/272c09c37fd9496b4cccb675fef329960fc87870

**Comment by cocktailz** [comment]
クローズします
