### ISSUE TITLE
WAIC-TEST-0043-01 リージョンとランドマークに名前 (name) を付けるために、aria-labelledby を使用する

### ISSUE THREAD

**Issue by bakera** [waic/as_test#197]
ARIA13 の事例 1「ページ上のテキストをもつランドマークを識別する」をベースにしたテスト
https://waic.jp/translations/WCAG21/Techniques/aria/ARIA13

**Comment by bakera** [comment]
余談ながら、2.0の事例1はマークアップが力強く間違っていて、pの中にh3を入れてしまっている。何やってるの
https://waic.jp/translations/WCAG-TECHS/ARIA13.html

2.1ではpがdivに修正されている。

**Comment by bakera** [comment]
相談したいこと:

- complementaryランドマークの上に本文を追加しています。
    - なにか要素がないと「ランドマークに突入した」という局面にならないため
    - 下にも文が必要かどうか悩みましたが一旦なしにしています。ランドマークを抜ける時に通知されるかをテストする必要があれば追加した方がいいかもしれません。
- ランドマーク最上部の見出しを aria-labelledby で結びつけているため、UA が aria-labelledby に対応していなくても見出しは普通に読まれます。見出しが読まれているのか、ランドマークの名前(name)が読まれているのかを区別しにくいかもしれません。

**Comment by nishimotz** [comment]
#198 マージしました。
