### ISSUE TITLE
WAIC-TEST-0002-02 リンクの中にテキスト、アイコン画像（代替テキストあり）の順で並べた場合

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#20]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/4724b0b1fb924c5569ba8edd1be75b9d6fb9e8f3

**Comment by cocktailz** [comment]
クローズします
