### ISSUE TITLE
WAIC-TEST-0003-01 複数のフォームコントロールにフォーカス移動順序を指定した場合

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#21]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/7ba93bba15c1b0c972fb7afa8b9647905e259489

**Comment by cocktailz** [comment]
クローズします
