### ISSUE TITLE
WAIC-TEST-0003-02 マークアップの順序とフォーカス移動順序が異なる場合

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#22]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/bad3f007610e65addf6b114b1e18e9dc49efebf8

**Comment by cocktailz** [comment]
クローズします
