### ISSUE TITLE
WAIC-TEST-0003-03 複数のリンクにフォーカス順序を指定した場合

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#23]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/498227cd820890458b60f1d9e7d859daabf78f0e

**Comment by cocktailz** [comment]
クローズします
