### ISSUE TITLE
WAIC-TEST-0090-01 / C12: フォントサイズにパーセントを使用する

### ISSUE THREAD

**Issue by sasak1ll** [waic/as_test#235]
C12
https://waic.jp/translations/WCAG21/Techniques/css/C12

**Comment by nishimotz** [comment]
スプレッドシートで C12 に 0090-01 が採番されていました。

**Comment by sasak1ll** [comment]
タイトル修正しました

**Comment by nishimotz** [comment]
大きさが変わらないものをあわせて表示し、特定の部分だけが変わることを確認させたい
