### ISSUE TITLE
WAIC-TEST-0121-01 / SCR16: 制限時間が切れようとしていることを利用者に警告するスクリプトを提供する

### ISSUE THREAD

**Issue by bakera** [waic/as_test#236]

**Comment by nishimotz** [comment]
スプレッドシートで SCR16 に 0121-01 が採番されていました。

**Comment by nishimotz** [comment]
Chrome の挙動と関係があるかも？
https://issues.chromium.org/issues/40058135

**Comment by kubosho** [comment]
上記のissueはOSがAndroidかつ、ステータスがWon't fix(obsolete)なので、デスクトップの非アクティブなChromeウインドウでダイアログが表示されない件とは違うかも。

**Comment by nishimotz** [comment]
* SCR16 の純粋なテストとする。つまり、警告メッセージが表示されることだけを確認する
* ウィンドウが非アクティブの場合もテストする

**Comment by nishimotz** [comment]
2.2.1 の延長に関して SCR16 を選ぶ場合は、充分な達成方法が「 SCR1 かつ SCR16 」であることに注意する。
