### ISSUE TITLE
WAIC-TEST-0003-04 複数のリンクに重複するフォーカス順序を指定した場合

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#24]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/ccd497a75f510694a8c849e7dd19e451eb5f5203

**Comment by cocktailz** [comment]
クローズします
