### ISSUE TITLE
WAIC-TEST-0004-01 イメージマップであることがユーザーに伝わるか

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#25]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/946cb96b38f113093c1bd53c2170c0a27d8525d6

**Comment by cocktailz** [comment]
クローズします
