### ISSUE TITLE
WAIC-TEST-0004-02 イメージマップに用いられている画像に付与した代替テキストの表示・読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#26]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by cocktailz** [comment]
期待される結果について、0004-03 との区別が明確になるように、イメージマップに用いられている画像のalt属性値を読み上げることが伝わるように文言を修正しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/c8d37576c1d2d7c530acbf90969320113511d5c3
https://github.com/waic/as_testfile2015/commit/ffe6cc27710d63194bbeaae5664417cc38b3916f

**Comment by cocktailz** [comment]
クローズします
