### ISSUE TITLE
WAIC-TEST-0004-03 イメージマップの各area要素に付与した代替テキストの表示・読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#27]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。
また表示・読み上げ内容の誤りを修正しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/98d1840d8d3a5803d2d8426da1180d08f5f9346f
https://github.com/waic/as_testfile2015/commit/323053f9d5feee808ae65598014d054e01b34c97

**Comment by cocktailz** [comment]
クローズします
