### ISSUE TITLE
WAIC-TEST-0004-04 イメージマップの各area要素がリンクであることが分かるかどうか

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#28]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/9c159bc6d096ce04bbb5f3aed731b2cfc550b385

**Comment by cocktailz** [comment]
クローズします
