### ISSUE TITLE
WAIC-TEST-0004-05 イメージマップの各area要素がリンクとして機能するか

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#29]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/a2790c21db1f3e4d962d06bd2f8c78f6dd714e37

**Comment by cocktailz** [comment]
クローズします
