### ISSUE TITLE
WAIC-TEST-0006-01 a要素に指定したリンクテキストの表示・読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#31]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。
また視覚閲覧環境に対するテストを不要としているため、テストのタイトルや目的から「表示」を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/716f27ebac5e579347692ff0ee9f2312477d7cc3

**Comment by cocktailz** [comment]
クローズします
