### ISSUE TITLE
WAIC-TEST-0006-02 リンク画像に指定した代替テキストの表示・読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#32]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/ca39d49b3838078b63309db70b96b45b76ad33f2

**Comment by cocktailz** [comment]
クローズします
