### ISSUE TITLE
WAIC-TEST-0006-03 リンクテキストを補足するtitle属性の表示・読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#33]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/83045ca534afbdbe7aff9b98fe4e79a65670ed77

**Comment by cocktailz** [comment]
クローズします
