### ISSUE TITLE
WAIC-TEST-0008-01 送信・実行ボタンに指定した代替テキストの表示・読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#36]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/17402fd20bcf90dcbb3c1b8e73b2b8813c66625f

**Comment by cocktailz** [comment]
クローズします
