### ISSUE TITLE
WAIC-TEST-0009-01 画像に指定した代替テキストの表示・読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#37]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/2910afa1c96837496e1e477421954aaaff2c1f0c

**Comment by cocktailz** [comment]
クローズします
