### ISSUE TITLE
WAIC-TEST-0010-01 caption要素に指定した表題の表示・読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#38]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/b877d7f9af662ebdc695fd5f07144bc9c2945740

**Comment by cocktailz** [comment]
クローズします
