### ISSUE TITLE
WAIC-TEST-0010-02 テーブルの開始および終了の読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#39]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/2b89b269da0135a2b25eb74da3c3bd0d83a56f80

**Comment by cocktailz** [comment]
クローズします
