### ISSUE TITLE
WAIC-TEST-0010-03 テーブルの行数および列数の読み上げ

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#40]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/0e9d4bbf69028aa73ae2d1ed84adfdb909c6d191

**Comment by cocktailz** [comment]
クローズします
