### ISSUE TITLE
WAIC-TEST-0010-04 現在いるテーブルセルと関連付けられている行見出しを確認する手段が提供されているか

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#41]

**Comment by cocktailz** [comment]
期待される結果において、NGとなる基準を削除しました。

**Comment by nishimotz** [comment]
対応するコミット
https://github.com/waic/as_testfile2015/commit/248b5371a381f88dcd652b48e98f2d98b2561f22

変更内容は文末マルの削除だけのようです。

**Comment by cocktailz** [comment]
クローズします
