### ISSUE TITLE
WAIC-TEST-0022-01　optgroup 要素を用いて select  要素内の option 要素をグループ化している場合の対応

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#5]

**Comment by cocktailz** [comment]
NVDA+Firefox では、alt+上下でセレクトメニューを開いてから上下キーで移動すると、optgroup のラベルを読んだり、同じグループ内にoption要素がいくつあって何番目か読んでいるが、optgroup 要素の個数や、何番目のoptgroup要素なのかは読まない。

**Comment by cocktailz** [comment]
PC-Talker + IE ではoptgroupのラベルを認識していない模様。
ブラウザ側で情報をとっていないか、伝えていないのではないか。

**Comment by cocktailz** [comment]
WAIC-TEST-0014ではulやolについてテストしているので、それにあわせるようにしてはどうか。

**Comment by cocktailz** [comment]
0014とあわせるとすると、
 - 全体的なサイズ感（optgroupなのかoptionなのかは別途議論するとして）
 - 各optgroup内にいくつoptionがあるか
ぐらいの期待されれう結果になるのではないか

**Comment by cocktailz** [comment]
option要素がどのoptgroup荷ぞkしているのかを知る手段が提供されているかどうか確認するテストとして再検討すr。

**Comment by cocktailz** [comment]
全体のサイズ感の話、グループ化のためにoptgroupを使うのであればoptgroup内のoption要素がいくつあるのかという情報も必要なのではないか。

**Comment by cocktailz** [comment]
ブラウザのサイズやレイアウトなどにもよるので、視覚的にもそれほど一覧性はないのではないか。

**Comment by cocktailz** [comment]
期待される結果の（３）を残すように修正。

**Comment by cocktailz** [comment]
期待される結果を修正し、あわせてテストの目的を修正しました。

**Comment by ma10** [comment]
「期待される結果」について、optgroup要素のlabel属性の内容を知る手段がある、というのを含めなくて良いかを検討した方が良いと思います。

手元のNVDA+Firefoxでは、 alt+↓で開いた状態で上下矢印キーを使うと、グループのラベル、グループ内のいくつ要素があるうちのいくつ目か、というのが読み上げられます。

**Comment by cocktailz** [comment]
フルーツから野菜へ移動した、
野菜から焼き菓子へ移動した。

または、今どのグループにいるか？

を知る手段があるかということですね。

**Comment by nishimotz** [comment]
すでに確認されている通りですが、項目移動時に「フルーツ グループ」「野菜 グループ」などとグループの変化を報告してくれるのは、NVDA + Chrome では非対応でした。

**Comment by cocktailz** [comment]
期待される結果に、optgroup 要素の label 属性値を知る手段があることを追加しました。

**Comment by nishimotz** [comment]
NVDA+Firefox での検証の補足ですが、
NVDA の設定「オブジェクト表示」「オブジェクト位置情報の報告」をチェックすると

* バナナ 2の4 レベル2
* 桃 3の4 レベル2
* みかん 4の4 レベル2

のような読み上げになるので optgroup の中での option の総数や現在位置などは把握できます。
チェックなしにすると「2の4」みたいな情報は読み上げません。

期待される結果の更新には影響なく、現状の説明に問題はないと思います。
