### ISSUE TITLE
テストの開始に向けて

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#61]
テストの開始に向けて作業・検討すべき内容をまとめました。
ご意見ある方は、このイシューにコメントしてください。

https://github.com/waic/as_testfile2015/wiki/%E3%83%86%E3%82%B9%E3%83%88%E3%81%AE%E9%96%8B%E5%A7%8B%E3%81%AB%E5%90%91%E3%81%91%E3%81%A6

**Comment by masuP9** [comment]
ありがとうございますー。今日ミーティング出れないのでチョットだけコメントします。

## 積み残し作業

それぞれ issue を作って担当者をアサインで良いと思いますー。

> GitHub pages からテストコードを閲覧できるようにする

なら私でもやれそうです。

## 検討事項

これも一つ一つ issue にしてもいいかもですね。

> - テストコードに適用されたCSS(jis-common.css)の是非

言い出したの僕だと思います。古いと言えば古いですが、優先順位としては低いんじゃないかなと思ってます。

> テスト結果の記載内容とフォーマット

出力フォーマットは、JSONがあれば [Can I use](https://caniuse.com/) 的なことができるし、ウェブページとしても出力できるので素敵だなぁって思いました。

## テスト結果の記載内容（案）

> テスト実施者（氏名、メールアドレス？）

いらないかなって思いました。すくなくとも GitHub で管理しているうちは分かりますし。

**Comment by bakera** [comment]
>GitHub pages からテストコードを閲覧できるようにする

なりゆきで、ひとまずmaster全部がみられるように設定しました。
例: http://waic.github.io/as_testfile2015/WAIC-CODE/WAIC-CODE-0001-01

**Comment by momdo** [comment]
上のURLは、正しくは
http://waic.github.io/as_test/WAIC-CODE/WAIC-CODE-0001-01
ですね。

**Comment by nishimotz** [comment]
上記に対応する説明はここから読めますね
http://waic.github.io/as_test/WAIC-TEST/HTML/WAIC-TEST-0001-01.txt

**Comment by bakera** [comment]
この内容は対応済みor他のissueが立っているので、このissueはクローズします。
