### ISSUE TITLE
今後の作業をmasterブランチをベースにして勧めるように変更する

### ISSUE THREAD

**Issue by ma10** [waic/as_test#62]
#61 に関連して、テスト・ファイルの見直し作業の進め方について、2018-01-26のミーティングで以下の方針に決定:

* 現在のdevブランチをmasterブランチにマージ
* 今後検討するテストやコードは、masterブランチの中の別のディレクトリーに移動
* 今後は作業ごとにmasterから別のブランチを作り、レビューが完了したものはmasterにマージ

**Comment by bakera** [comment]
masterにマージ済みで完了しているのでクローズします。
