### ISSUE TITLE
テスト結果フォームの作成

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#63]
ASテスト結果を入力するフォームをGoogle Formで作成しました。
また、送信先としてスプレッドシートを設定しています。

**Comment by cocktailz** [comment]
「支援技術」はあえて必須ではなくしている（というのを昨日作業したのに忘れていた）。

**Comment by cocktailz** [comment]
バージョン表記については、OSもブラウザも支援技術も、バージョン番号を表示するダイアログの内容をコピーしてそれを張ってもらうのがよいのではないか。

**Comment by cocktailz** [comment]
手順化しやすいし、OSの場合、自動更新だったりして本人が意識していないこともある。

**Comment by cocktailz** [comment]
ではこれでいきます。

**Comment by cocktailz** [comment]
「操作内容とその結果」はまとめすぎではないか。
音声閲覧環境お場合、テストの手順と読み上げのフィールドが混在していると判断がしづらくなる。

**Comment by cocktailz** [comment]
期待される結果の各項目について、
何を確認しようとして、どんな操作をして、どんな結果が得られて、どう判断したかを記録する必要があるのではないか。

**Comment by cocktailz** [comment]
実施者が入力欄を増やすには、セクションを追加するとできそうな気がする。
5個ぐらいの条件分岐を作っておいて、期待される結果があるところまで記入させるのはどうか。

**Comment by cocktailz** [comment]
操作内容は再現するために重要。また操作方法を公開することでその方法を知らなかった人がそれをきっかけに学ぶこともできる。

**Comment by cocktailz** [comment]
用語集を含めたテスト実施方法へのリンク、入力例も記載したほうがよい。

**Comment by cocktailz** [comment]
実施者名とメールアドレスについては、今後WAICメンバー以外がテストを行ってくださることを考えると必要。

**Comment by cocktailz** [comment]
テストファイル、テストコードの番号にはバージョン表記が必要ではないか。
日付をバージョン表記に使えるのではないか

**Comment by cocktailz** [comment]
実施日についてh、あとで処理をしやすいようにDate Pickerなりを使う方がよいのではないか。

また子のフォームがどうしても使えない場合のメールによる受付などもあったらよいのではないか。

**Comment by cocktailz** [comment]
テストファイル、テストコードのバージョン番号を追加する件について、日付のあとのプラス1桁追加する。テストファイルやコードのファイル名そのものをかえるのか、他の方法をとるのか。

**Comment by cocktailz** [comment]
日付ではなく単純に1とか2とかシリアル番号でもいいかもしれない。

**Comment by cocktailz** [comment]
WAIC-TEST, WAIC-CODEも入力させるのか。

**Comment by cocktailz** [comment]
番号が数字だけになると見返すときに誤る可能性が出る。

**Comment by cocktailz** [comment]
- テストファイルはそのまま
 - テストコードという呼び方はしないようにする
 - フォームから記入してもらうのはテストファイルの番号とバージョン情報のみにする
 - テストファイルから対処のコードがたどれるようなバージョン管理方法にする

**Comment by cocktailz** [comment]
顔にさかのぼってテスト出kる日露はあるのではないか

**Comment by cocktailz** [comment]
我々がさかのぼれるすべを知っていればよくて、それを常に更新しておく必要はないの絵はないか。

**Comment by cocktailz** [comment]
タグを埋め込む、あるいはスナップショットで対応できる。往診頻度によって運用補法も変わってくる。

**Comment by cocktailz** [comment]
- テストコードの更新をするときに、テストファイルの最終更新日とバージョン番号を更新する。その手間や漏れを減らすためにCIを使うという手はある。

**Comment by cocktailz** [comment]
テストコードを更新したときに、それを参照しているテストファイルを確認できる表などはないので作成する。

**Comment by cocktailz** [comment]
バージョン番号は1とか2とかで、今はよいのではないか。

**Comment by cocktailz** [comment]
作成日、公開日は削除。

**Comment by cocktailz** [comment]
テストファイル→テストケース

**Comment by cocktailz** [comment]
リポジトリ名も2015をとってas_testにする。

**Comment by cocktailz** [comment]
期待される結果の各項目をコピペする必要はあるか？
スマートさには欠けるが仕方ないようにも思える。

**Comment by nishimotz** [comment]
ためしに埋めてみると。。。

https://github.com/waic/as_testfile2015/blob/master/WAIC-TEST/HTML/WAIC-TEST-0012-01.txt

期待される結果(1)の内容

```
それぞれのテキストボックスにフォーカスを移動した際、以下のリストのとおりに関連付けられたラベルを知るための何らかの手段が提供されている
1.のテキストボックス：ラベル「姓」
2.のテキストボックス：ラベル「名」
3.のテキストボックス：ラベル「住所」
4.のテキストボックス：ラベル「電話番号」
```

操作内容

```
テキストボックス「姓」にTabキーで移動し、さらにTabキーを３回押す
```

得られた結果

```
順番に「ほげ」「ほげ」「ほげ」「ほげ」と読み上げる
```

**Comment by cocktailz** [comment]
期待される結果の番号表記にゆれがある

**Comment by cocktailz** [comment]
操作内容と得られt結果についても何か補足がほしい。
記入例の詳細さとのバランスをどうするか。

**Comment by cocktailz** [comment]
10月のWG2議事録に基づき、以下の修正を行いました。

(1) 例の文言が古いので、表記ゆれ修正後の内容に差し替える
(2) 備考に記入欄がないので追加する
(3) 「次のセクションへ進む」ではなく「次へ」
(4) テスト実施者が「期待される結果」をコピペする際に、音声閲覧環境なのか視覚閲覧環境なのか迷わないように「期待される結果（1）」の説明を追記する

(4) については、テスト結果 (1) の「期待される結果 (11」「操作内容」「得られた結果」の説明文を以下のように修正しました。

期待される結果 (1) の説明：
ビジュアルブラウザのテストを行う場合はテストケースの「期待される結果 (視覚閲覧環境)」の最初の項目について、以下を入力してください。スクリーンリーダーのテストを行う場合はテストケースの「期待される結果 (音声閲覧環境)」の最初の項目について、以下を入力してください。

期待される結果 (1) ；
「期待される結果 (視覚閲覧環境)」又は「期待される結果 (音声閲覧環境)」の1. をコピーします。例（WAIC-TEST-0001-01 の場合）：（視覚閲覧環境）代替テキストやコンテンツと誤解されるようなファイル名や URL などが表示されない　（音声閲覧環境）アイコン画像の代替テキストは何も読み上げられず、リンクテキスト “ウェブアクセシビリティ基盤委員会公開サイト” のみが読み上げられる

操作内容：
マウスやキーボードなどで操作した内容を入力してください。例（WAIC-TEST-0001-01 の場合）： （視覚閲覧環境）ブラウザを画像非表示に設定変更し、表示内容を確認した（音声閲覧環境）リンク「ウェブアクセシビリティ基盤委員会公開サイト」に Tab キーで移動した。

得られた内容：
上記「操作内容」に入力した操作の結果、得られた内容を入力してください。例（WAIC-TEST-0001-01 の場合）：（視覚閲覧環境）リンクテキスト「ウェブアクセシビリティ基盤委員会公開サイト」のみが表示され、画像のファイル名や URL 等は表示されなかった。（音声閲覧環境）リンクテキスト「ウェブアクセシビリティ基盤委員会公開サイト」のみ読み上げられた。

澤田さんにはレビューいただいておりますが、ほかのみなさんいかがでしょうか。

**Comment by cocktailz** [comment]
- AS テスト結果入力フォーム
 - メールによる送信についてのページ

上記2つのURLを追加する。

**Comment by cocktailz** [comment]
クローズします
