### ISSUE TITLE
jis-common.cssの扱いについて

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#64]
これまで作成したすべてのテストコードに対して、<a href="https://github.com/waic/as_testfile2015/blob/master/jis-common.css">jis-common.css</a>が適用されています。
これは以前に制作したテストファイルのCSSをそのまま適用しているのですが、2017年11月のWG2で「（特に視覚閲覧環境での）テスト結果に影響を及ぼすのではないか?」との議論がありました。

内容を確認したところ、現在のテストコードと関連するのは7行目

body { margin: 0; padding: 0; }

および84行目

.jis-testcode { background-color: #f9f5de; border: solid 1px #006; border-left: solid 6px #006; margin-top: 5px; margin-left: 30px; padding: 14px; }

の2か所です。

これをみるとテスト結果に影響を及ぼしそうなプロパティはなさそうなのでこのまま適用してもよいかと思いますが、みなさんいかがでしょうか。

**Comment by masuP9** [comment]
テスト結果に影響を及ぼしそうなプロパティは無さそうに見えますが、何かあった時に問題を切り分けるのが大変そうなので、個人的にはスタイルがあたってない（UAスタイルシートのみが当たっている状態）が望ましいかなと思っています。

**Comment by cocktailz** [comment]
最近のCSSはスクリーンリーダーにも影響を与えるのではないか。

**Comment by cocktailz** [comment]
jis-common.cssははずす

**Comment by cocktailz** [comment]
個別にstyleを当てているテストコードについては、その必要性を再度確認する（いしき）

**Comment by cocktailz** [comment]
ブランチ remove-jis-common-css を作成しました。
https://github.com/waic/as_testfile2015/tree/remove-jis-common-css

以下の作業を行います。
 - jis-common.css を削除
 - テストコードでCSSを適用している link 要素を削除

**Comment by cocktailz** [comment]
作業完了しました。
テストコード自体にstyle要素でスタイルが適用されている箇所について。

WAIC-CODE-0012-01.html

<style>
#labelrow label {
  margin: 1em 9em 0 0;
}
.inputInLabel {
  margin: 0.5em 0;
}
</style>

ラベルとコントロールの関連付けに関するテストです。
labelrow は2つのラベル「姓」と「名」のマージンを取ることで、その下のテキストボックスと位置が合うように調整しています。
inputInLabelはシンプルな上下マージンです。

このテストでは、スクリーンリーダーがラベルとコントロールの位置によってその関係性を推測して読み上げるのではなく、マークアップによる関連付けを正しく解釈しているかという点も確認していますが、上記style要素とは関係ないので削除してよいかと思います。いかがでしょうか。

**Comment by cocktailz** [comment]
すみません、作業完了というのは間違いでした。wip内のコードについて作業が残っていました。

**Comment by cocktailz** [comment]
jis-common.css を適用している link 要素を削除しました。#64
レビューをお願いします。2名以上の方からLGTMをいただけたら master にマージします。

**Comment by nishimotz** [comment]
LGTM

**Comment by SawadaStdDesign** [comment]
LGTM（こうですか？ 削除されていることは確認しました。

**Comment by bakera** [comment]
masterにマージされたのでクローズします。
