### ISSUE TITLE
テスト実施時のUA設定について

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#65]
テストを実施する際、実施者のブラウザや支援技術の設定によってテスト結果に影響が出るのではないかと懸念しています。

 - テスト実施者はブラウザや支援技術の仕様や挙動をある程度知っている人
 - テスト結果が俗人的にならないようにしたい

という前提条件で、テスト実施時のUA設定について何らかの条件や確認事項を設けるのか、それほど気にしなくてよいのか議論したいです。

また前者になった場合、どのようにそれを伝えるかも考えたいです。

**Comment by cocktailz** [comment]
テストを行う際の一般的なルルを設けておいて、そこからはずれた設定でテストする場合はそのことを特記事項なり備考ありに記載する、というのはどうか。

**Comment by cocktailz** [comment]
スクリーンリーダーユーザーはあまり初期設定のままで使っていないのではないか。そもそもデフォルト値がよくわからないのではないか。

**Comment by cocktailz** [comment]
ブラウザについてはセーフモードやプライベートモードなどで使ってもらうのがよいのではないか。
ブラウザの設定はできるだけ変えない状態でテストするのがよいのではないか。

**Comment by cocktailz** [comment]
スクリーンリーダーについてはデフォルト値でテストするのは難しい。
一般的な設定だとうまくいかないけど、この設定を変更したらうまくいｔｔ、というような内容を記載で切る仕組みを作る、あるいはこちらで再現するに足る情報尾得られればよいのではないか。

**Comment by cocktailz** [comment]
テストを実施するにあたって特別な設定をした場合あそれを書いてもらうようにするのはどうか。

**Comment by cocktailz** [comment]
テストの実施方法や記入例の説明で、初期設定8に近い9環境を示したうえで、それ以上の設定をしている場合には記載してもらう仕組みを作る方向はどうか。

**Comment by cocktailz** [comment]
設定尾記載は実施環境の中で行う。

**Comment by nishimotz** [comment]
まだ NVDA + Firefox のことしか考えていませんが、設定の違いでテストが成り立たなくなるケースがどのくらいありそうか、確認しています。

* 全体を通して音声エンジン「音声なし」以外（適切に日本語を読み上げる音声）を選択しないと、「読み上げる」という結果が成り立たない
* 書式とドキュメント情報 → 要素 → リンク：チェック（これがチェックなしの場合に、例えば WAIC-TEST-0004-04.txt の「リンクだとユーザーに伝わる」が成り立たない）

**Comment by cocktailz** [comment]
10月のWG2でいったん落ち着かせることにしたのでひとまずクローズします。
今後、テストをしてみて、追加で設定などが必要になった場合は再度オープンします。
