### ISSUE TITLE
「AS情報を作成するためのテスト実施方法」について

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#68]
テスト実施方法を説明するテキストを作り始めました。
ドラフトをwikiに書き始めています。

https://github.com/waic/as_testfile2015/wiki/AS%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E6%96%BD%E6%96%B9%E6%B3%95

子のイシューで内容や書きぶりについて相談できればと思います。

**Comment by nishimotz** [comment]
用語 #12 を参照しつつ説明する

**Comment by nishimotz** [comment]
今日の WG2 までにやると言いながら、いまごろ手を付けています。
#65 とかぶってますが、まず NVDA の設定ダイアログの操作を書いています。

https://github.com/waic/as_test/wiki/AS%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E6%96%BD%E6%96%B9%E6%B3%95

**Comment by ksdnakano** [comment]
「ブラウザとバージョンの入力方法」に、Internet Explorerを追加しました。
「支援技術とそのバージョンの入力方法」と「支援技術の一般的な設定」にPCTalkerを追加しました。

**Comment by nishimotz** [comment]
議論したこと
* Chrome のバージョン確認方法は書く（書いた）
* JAWS / iOS Safari は必要と思うが、次の段階の作業とする

**Comment by nishimotz** [comment]
下記は @cocktailz さんにたたき台をお願いします

* このテストについて
* テスト実施方法

**Comment by cocktailz** [comment]
以下の内容を追記しました。

 - このテストについて
 - テスト実施方法
 - 結果の入力

また全体的に見直し、修正をしています。レビューをお願いします。

https://github.com/waic/as_test/wiki/AS%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E6%96%BD%E6%96%B9%E6%B3%95

**Comment by cocktailz** [comment]
唐突にテストケース、テストコードという用語が出てくるのがわかりづらい。実態とつながるような書き方をしないといけない。

**Comment by cocktailz** [comment]
README.md の中にあるディレクトリ構成を再掲するなどするとわかりやすくなるか。

**Comment by cocktailz** [comment]
READMEを参照するように冒頭で文章を追加する。
