### ISSUE TITLE
著作権メタデータについて

### ISSUE THREAD

**Issue by momdo** [waic/as_test#70]
クリエイティブコモンズであることを現状では次のコードで表現していますが
https://github.com/waic/as_test/blob/7303fcc1f5df7b614a66169177ddc67fa6ce4faf/WAIC-CODE/WAIC-CODE-0001-01.html#L6

より明示的に次のようにしてはどうでしょうか。（以下は現行の[CC BY\-SA 2\.1 JP](https://creativecommons.org/licenses/by-sa/2.1/jp/)ですが、[CC BY\-SA 4\.0](https://creativecommons.org/licenses/by-sa/4.0/deed.ja)に更新してもよいかもしれません。）
```html
<link rel="license" http://creativecommons.org/licenses/by-sa/2.1/jp/">
```
あわせて、著者がWAICであることも明示してもよいかもしれません：
```html
<meta name="author" content="ウェブアクセシビリティ基盤委員会（WAIC）">
```

参考リソースHTML Standard訳:
https://momdo.github.io/html/links.html#link-type-license

**Comment by nishimotz** [comment]
属性は href でいいらしい
```
<link rel="license" href="http://creativecommons.org/licenses/by-sa/2.1/jp/">
```

**Comment by cocktailz** [comment]
やりましょう。

**Comment by cocktailz** [comment]
マージしたのでクローズします。
