### ISSUE TITLE
AS 情報の作成方法

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#78]
ASテスト結果をもとに作成するAS情報の在り方、整備の仕方について議論します。
以下の wiki に材料になる資料を置きましたのでご確認ください。

https://github.com/waic/as_test/wiki/AS-%E6%83%85%E5%A0%B1%E3%81%AE%E4%BD%9C%E6%88%90%E6%96%B9%E6%B3%95

**Comment by akiyamaa-cnt** [comment]
2020年版 as情報公開にむけた議論は実施済み。
