### ISSUE TITLE
WAIC-TEST-0024-01 nav 要素への対応

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#8]

**Comment by cocktailz** [comment]
nav 要素のセマンティクスをスクリーンリーダーが伝えているかのテスト。

**Comment by ma10** [comment]
ナビゲーションの開始位置と終了位置が分かる必要があるのではないか。

**Comment by nishimotz** [comment]
NVDA での検証は、
ナビゲーションに入ったことは Firefox, Chrome, IE11 すべて
「ナビゲーション ランドマーク リンク ホーム」のようにわかりますが、
ナビゲーションから出たことはどのブラウザでも報告なしです。

一番下から上に移動すると
「ナビゲーション ランドマーク リンク お問い合わせ」のように、
下からナビゲーションにはいったことがわかります。

**Comment by masuP9** [comment]
https://github.com/waic/as_test/blob/master/WAIC-CODE/WAIC-CODE-0024-01.html
https://github.com/waic/as_test/blob/master/WAIC-TEST/HTML/WAIC-TEST-0024-01.md

**Comment by masuP9** [comment]
- 期待される結果を main 要素のテスト WAIC-TEST-0026-1 と合わせる
- テストコードの nav の次の要素を <a> にする
