### ISSUE TITLE
WAIC サイトでの協力依頼ページ作成

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#85]
ASテストの開始と協力依頼について、WAICサイトでお知らせするページの文案を Wiki にアップしています。今週中をめどにご意見ください。

https://github.com/waic/as_test/wiki/AS%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E3%81%B8%E3%81%94%E5%8D%94%E5%8A%9B%E3%81%AE%E3%81%8A%E9%A1%98%E3%81%84

**Comment by SawadaStdDesign** [comment]
近い位置で「テスト結果をメールでお送りいただく場合〜」が繰り返されていますので、「なお、テスト結果をメールでお送りいただく場合には、「記載事項及び記載方法」をご確認ください。」は削除しても構わないのではないでしょうか？

**Comment by SawadaStdDesign** [comment]
表記ゆれがあります。
「記載事項及び記載方法」
「記載項目及び記載事項」
「記載項目と記載方法」

**Comment by SawadaStdDesign** [comment]
「記載項目と記載方法」以下の内容および体裁が、Wiki「AS情報を作成するためのテスト実施方法」の「テスト結果の入力」とだいぶ違っていますが、共通化されると考えてよろしいでしょうか？
個別に修正すると手間ですし、危険かなと思いますので。

**Comment by cocktailz** [comment]
以下修正しました。

（１）「なお、テスト結果をメールでお送りいただく場合には、「記載事項及び記載方法」をご確認ください。」の削除
（２）表記ゆれを「記載項目及び記載方法」で統一
（３）「テスト結果をメールでお送りいただく場合について」以下の記載項目及び記載方法について、Wiki「AS情報を作成するためのテスト実施方法」の内容と共通化

**Comment by SawadaStdDesign** [comment]
（１）〜（３）の修正内容について確認しました。
問題ございません。

**Comment by cocktailz** [comment]
澤田さん、ありがとうございます。

テスト対象について、テストタイトル、テストケース、テストコードの対応表を追加しました。
この内容で WAIC サイトへの掲載準備を進めていただこうと思います。

**Comment by cocktailz** [comment]
すでにWAICサイトに掲載されましたのでクローズします
