### ISSUE TITLE
AS 情報の作成に向けた準備

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#86]
ASテスト結果をもとに作成するAS情報の構成や、「見解」「代替／推奨方法」を作成する際の基準、作業フローなどを固めていきます。以下の Wiki をベースに作業を進めます。

次回のWG2（12月25日予定）までにある程度固めておきたいと思います。

https://github.com/waic/as_test/wiki/AS-%E6%83%85%E5%A0%B1%E3%81%AE%E4%BD%9C%E6%88%90%E6%96%B9%E6%B3%95

**Comment by akiyamaa-cnt** [comment]
2020年版の as情報公開にむけた議論は実施済み。
