### ISSUE TITLE
WAIC-TEST-0007-02 form要素のaction属性に指定されているサーバーが存在しない

### ISSUE THREAD

**Issue by hideki-a** [waic/as_test#88]
テスト上必要と思われる jisx8341test.urabanezu.com のサーバーに接続できませんでした。

※Twitterでのやりとりがございます。
https://twitter.com/bakera/status/1078591642788028416

**Comment by nishimotz** [comment]
#92 で対応しました。ご確認ください。

**Comment by hideki-a** [comment]
ご対応ありがとうございます。
セレクトメニューで選択したページに移動することを確認いたしましたのでクローズします。
