### ISSUE TITLE
WAIC-TEST-0001-01 視覚閲覧環境の期待される結果に表示内容を入れたい

### ISSUE THREAD

**Issue by bakera** [waic/as_test#89]
WAIC-TEST-0001-01で、視覚閲覧環境の期待される結果が以下のようになっていますが、

>代替テキストやコンテンツと誤解されるようなファイル名や URL などが表示されない

「表示されない」という書き方のため、何が表示されていれば妥当なのかがわかりにくいです。
音声環境の方には以下のように、読まれるべき内容が書かれています。

>アイコン画像の代替テキストは何も読み上げられず、リンクテキスト “ウェブアクセシビリティ基盤委員会公開サイト” のみが読み上げられる

視覚閲覧環境もこれに合わせ、以下のようにしてはどうでしょうか。

代替テキストや、コンテンツと誤解されるようなファイル名や URL などは表示されず、リンクテキスト “ウェブアクセシビリティ基盤委員会公開サイト” のみが表示される

**Comment by SawadaStdDesign** [comment]
たしかにそうですね。良いと思います！

WAIC-TEST-0001-02、WAIC-TEST-0001-03 も同様ですね。

**Comment by cocktailz** [comment]
たしかに、合わせたほうが分かりやすいですね。

**Comment by cocktailz** [comment]
マージしたのでクローズします。
