### ISSUE TITLE
WAIC-TEST-0025-01 figure 要素及び figcaption 要素への対応

### ISSUE THREAD

**Issue by cocktailz** [waic/as_test#9]

**Comment by cocktailz** [comment]
figure 要素及び figcaption 要素のテスト。

テストコードがとてもシンプルですが、これ以外にテストしたほうがいいケースなどあればコメントください。
期待されるけ化などについてのコメントももちろんOKです。

**Comment by Morokuma0406** [comment]
table 要素と caption 要素の扱いに準ずるか、または単純に、差しかかった時に通知されるか否かで良いと思います。

1. figure 要素に差し掛かった時に、それが figure 要素であることを知るための何らかの手段が提供されているか？
2. figcaption 要素に差し掛かった時に、それが figure 要素であることを知るための何らかの手段が提供されているか？

今のスクリーンリーダーでは認識していないですけど…

**Comment by ma10** [comment]
figureについては、図だけでなくコードのようなテキストが入る可能性もあると思うので、先頭と末尾を特定できる必要もあると思います。

**Comment by cocktailz** [comment]
先頭と末尾を特定できるのは確かに必要ですね。

**Comment by cocktailz** [comment]
期待される結果を以下のようにしてみました。

以下の(1)から(3)をすべて満たしている。
(1) figure 要素に差し掛かったときに、そのことが通知される
(2) figure 要素の先頭及び末尾を知るための何らかの手段が提供されている
(3) figure 要素内のコンテンツと、figcaption 要素が関連していることを知るための何らかの手段が提供されている(?)

(3) はtable 要素とcaption 要素のように関係性を理解できるような情報の伝え方になっているかというのをテストしたほうがいいかもと思って書いてみmした。

https://github.com/waic/as_testfile2015/blob/dev/WAIC-TEST/HTML/WAIC-TEST-0025-01.txt

**Comment by ma10** [comment]
> (3) figure 要素内のコンテンツと、figcaption 要素が関連していることを知るための何らかの手段が提供されている(?)
> (3) はtable 要素とcaption 要素のように関係性を理解できるような情報の伝え方になっているかというのをテストしたほうがいいかもと思って書いてみmした。

figcaption要素は必ずfigure要素の中にあるはずなので、figure要素の中身について、それがfigcaption要素の内用なのかそうでないのかを判別できるようになっていれば良いような気がしますがどうでしょうか?

**Comment by cocktailz** [comment]
NVDA + Firefox 及び PC-Talker + IE はいずれもfigure 及び figcaption を解釈していない模様。

ナレーター+Firefox だと「グループ」と読んでfigcaption を読み、imgのaltを読み、最後に再度figcaptionを読んでいる模様。

期待される結果の(3)は不要?

**Comment by cocktailz** [comment]
JAWS16 + Firefox だと「グループ」「グループ修了と読むが、
JAWS16 + IE だと読まない。

**Comment by cocktailz** [comment]
figcaption がfigureの先頭にあるか末尾にあるかという情報は必要か?

**Comment by cocktailz** [comment]
仮に、以下のようにしてみました。

以下の(1)から(3)をすべて満たしている。
(1) figure 要素に差し掛かったときに、そのことが通知される
(2) figure 要素の先頭及び末尾を知るための何らかの手段が提供されている
(3) figcaption 要素に差し掛かったときに、そのことが通知される
(4) figcaption 要素の先頭及び末尾を知るための何らかの手段が提供されている

**Comment by akiyamaa-cnt** [comment]
* 下記 2つのテストファイルを作成
    * figure 要素の先頭に figcation
    * figure 要素の末尾に figcation

**Comment by SawadaStdDesign** [comment]
プルリクをマージしましたのでクローズします。
