### ISSUE TITLE
WAIC-TEST-0016-01の判断方法が不明

### ISSUE THREAD

**Issue by bakera** [waic/as_test#91]
WAIC-TEST-0016-01の期待される結果が
「英語の音声合成エンジンを用いて読み上げられる」
なのですが、その読み上げが「英語の音声合成エンジン」なのかどうかを判断する方法が不明という意見がありました。
確かに不明なので、判断方法の例などがあれば掲載したいところです。

**Comment by nishimotz** [comment]
改善案
* 英語の文章ではなく数字の 12345 をコンテンツにする
* lang を en と ja にしたものをそれぞれ -01 / -02 としてファイルを2つ作る
* これらが異なった読まれ方をすればよい、という判断方法にする
