### ISSUE TITLE
WAIC-CODE-0017-01のiframeのsrcがHTTPSになっていない

### ISSUE THREAD

**Issue by bakera** [waic/as_test#95]
澤田さんより以下のようなご指摘をいただいた。
>AS テストのレビューをしているんですが、今更ながら WAIC-CODE-0017-01 の iframe の src の URL がリンク切れ（http:// なので）してて表示できてませんね。VoiceOver の挙動としては NG なので、一応テストはできてますけど。

**Comment by bakera** [comment]
HTTP→HTTPSにする必要があるものをすべてチェックしたいですね。

**Comment by bakera** [comment]
たとえば、
<link rel="license" href="http://creativecommons.org/licenses/by-sa/2.1/jp/">
これも今やhttpsにするべきもののはず。む

**Comment by bakera** [comment]
WAIC-CODE-0019-03にあるこれも、
```
<td><a href="http://www.ciaj.or.jp/access/web/">8,500円</a></td>
```
https://waic.jp で良いですよね。

**Comment by bakera** [comment]
http:の残りは2つ。

WAIC-CODE-0008-01:
```
<form action="http://example.com/prog/text-read" method="post">
```
WAIC-CODE-0018-03:
```
<form action="http://example.com/prog/text-read" method="post">
```

これらはダミーと思われるのでいったんこのままとします。
(waic.jp にダミーの受けCGIをおいてもいいのかもしれません。)

**Comment by momdo** [comment]
脇にそれますが、ライセンスについてCC 2.1なのは個人的に引っかかっているところですが、最新版にしなければならない、というわけでもないのですね。
[13. 2.1など最新版ではない日本語ライセンスをそのまま使っているとまずいでしょうか？ 最新版に変える必要がありますか？ | FAQ　よくある質問と回答 | クリエイティブ・コモンズ・ジャパン](https://creativecommons.jp/faq/#i13)

**Comment by bakera** [comment]
ライセンスはあまり気にしていませんでしたが、一度見直しても良いですね。
